### ISSUE TITLE
WES Style Data - Variant Inserts Missing with `-v` option on. 

### ISSUE THREAD

**Issue by MikeWLloyd** [ncsa/NEAT#48] opened 2022-03-15 00:53 UTC
I am trying to generate WES style data to ensure a variant calling pipeline is functioning properly.

I first ran the simulator with the '-tr' option pointing to my bed file with WES regions. However, the inserted variants in the resulting truth file cover the genome, and not just the target regions. 

For my testing, I would like to check precision/recall in only those regions with target coverage, and not complicate my testing with off target variants. Therefore, I intersected the gold standard VCF against my WES regions. I then ran NEAT a second time specifying the intersected VCF file from the first run as the `-v` option.  

In my results I saw ~40-50% recall and 98% precision. In trying to diagnose the poor recall, I see the following behavior in the data from NEAT: 

Properly called variant: 
![correct_call](https://user-images.githubusercontent.com/19394970/158285220-58c7998e-f607-4fb0-a380-84ddb54e18ba.png)

Missing variant: 
![missing_call](https://user-images.githubusercontent.com/19394970/158285126-1d40a5e3-749f-4170-9edd-edd0486d1b9e.png)

As you can see for the missing variant, no bases were altered, and therefore no call was made. 

It makes perfect sense that a call wasn't made where there was no inserted variant; however, I would expect when you specify the `-v` option that all variants in the VCF would be used. Is this not the case?

**Comment by MikeWLloyd** [comment] 2022-03-15 00:59
first post the pictures were corrupted. fixed it in the edit.

**Comment by MikeWLloyd** [comment] 2022-03-15 01:09
It drops the 'WP=0/1' calls specifically.

**Comment by joshfactorial** [comment] 2022-03-15 03:40
I'll look into preserving the information in the input vcf. In order to make the simulation exclude targeted regions, there is a setting --discard-offtarget. It's lower down the list and easy to miss, but it will set the coverage outside of the targeted regions to 0.

**Comment by joshfactorial** [comment] 2022-03-15 03:41
I can double check on the input variants. The only reason I believe they get excluded is if the reference doesn't match what the VCF shows. But I can look at the code there again.

**Comment by joshfactorial** [comment] 2022-03-15 03:49
The stdout should have showed a summary of the input variants like this:

5 variants skipped...
                - 2 ref allele does not match reference
                - 1 attempting to insert into N-region
                - 2 alt allele contains non-ACGT characters

If that's not the case let me know. I may need to examine the input file or at least the variant in question.

I forgot there's also code that filters out variants that are filtered out (anything other than '.' or 'PASS'). That prints out a message like this:

 found 15 valid variants in input vcf.
    5 variants skipped: (qual filtered / ref genotypes / invalid syntax)
    1 variants skipped due to multiple variants found per position

**Comment by MikeWLloyd** [comment] 2022-03-15 11:29
@joshfactorial from the first run, in the gold VCF that is output, NEAT assigns the WP INFO to each variant call. In the second run, NEAT will insert all variants that NEAT called WP=1/0 from the first run, and excludes (or skips) all variants that NEAT called WP=0/1. I can post more screenshots later this am to show what I mean, if that was confusing. I need to try removing the ‘WP’ info and run the insertion that way. I suspect without WP, it would insert all variants.

**Comment by MikeWLloyd** [comment] 2022-03-15 13:14
found 26125 valid variants in input vcf.
 * 25536 variants skipped: (qual filtered / ref genotypes / invalid syntax)
 * 5 variants skipped due to multiple variants found per position

**Comment by joshfactorial** [comment] 2022-03-15 14:00
Correct, WP is NEAT's genotype, inserted during mutation. It should be able to pick up 0/1, though. That's not the expected behavior. For now try using a sed or awk command to delete the WP from the info column:

```
sed "s/WP=.*/./" smallest.vcf > smallerest.vcf
```

**Comment by joshfactorial** [comment] 2022-03-15 14:02
```
user@puter:~/Documents/neat_data$ cat smallest.vcf 
CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	10184	.	CCTA	C	.	PASS	WP=1/0
chr1	10204	.	T	C	.	PASS	WP=0/1
chr1	10209	.	C	A	.	PASS	WP=1/0
chr1	10231	.	C	T	.	PASS	WP=1/0
chr1	10235	.	T	C	.	PASS	WP=1/0
chr1	10244	.	C	T	.	PASS	WP=1/0
chr1	10278	.	C	T	.	PASS	WP=0/1
chr1	10301	.	C	T	.	PASS	WP=0/1
chr1	10395	.	A	G	.	PASS	WP=1/0
user@puter:~/Documents/neat_data$ sed "s/WP=.*/./" smallest.vcf
CHROM	POS	ID	REF	ALT	QUAL	FILTER	INFO
chr1	10184	.	CCTA	C	.	PASS	.
chr1	10204	.	T	C	.	PASS	.
chr1	10209	.	C	A	.	PASS	.
chr1	10231	.	C	T	.	PASS	.
chr1	10235	.	T	C	.	PASS	.
chr1	10244	.	C	T	.	PASS	.
chr1	10278	.	C	T	.	PASS	.
chr1	10301	.	C	T	.	PASS	.
chr1	10395	.	A	G	.	PASS	.
```

**Comment by joshfactorial** [comment] 2022-03-15 14:18
I've pushed a fix to master for the WP field, I think. You can pull the latest and try or strip off WP and try again.

**Comment by MikeWLloyd** [comment] 2022-03-15 14:20
Thanks! Will give it a go, and will reopen the issue if I am still having trouble.

**Comment by MikeWLloyd** [comment] 2022-03-15 14:25
```
python NEAT/gen_reads.py \
> -r chrM.fa \
> -R 150 \
> -o Homo_sapiens.GRCh38_simVar_60x_$filename \
> -c 120 \
> -to 0.02 \
> -E 0.001 \
> -M 0 \
> --vcf \
> -v Homo_sapiens.GRCh38_simVar_60x_ALLchr_golden_WES_intersect.recode.vcf \
> --pe 350 30 \
> -tr hg38_liftover_agilent_SureSelect_V4_pChrM_PrimaryOnly_probes_sorted.bed

Using default sequencing error model.
Warning: Quality scores no longer exactly representative of error probability. Error model scaled by 0.151 to match desired rate...
Warning: Read length of error model (101) does not match -R value (150), rescaling model...
Using default gc-bias model.
Using artificial fragment length distribution. mean=350 std=30
Index not found, creating one...
0.001 (sec)
--------------------------------
reading input VCF...

Traceback (most recent call last):
  File "/fastscratch/lloydm/NEAT/gen_reads.py", line 896, in <module>
    main()
  File "/fastscratch/lloydm/NEAT/gen_reads.py", line 305, in main
    (sample_names, input_variants) = parse_vcf(input_vcf, ploidy=ploids)
  File "/gpfs/ctgs0/fastscratch/lloydm/NEAT/source/vcf_func.py", line 116, in parse_vcf
    gt_eval = gt.replace('|').split('/')
AttributeError: 'list' object has no attribute 'replace'
```

**Closed** 2022-03-15 16:06 UTC

**Comment by joshfactorial** [comment] 2022-03-15 18:14
That's definitely something on my list to improve in the next release.
